---
title: "PEC1_Datos Ómicos"
author: "Fernando Santiago Hontoria"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r 1, echo =TRUE}

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
if (!requireNamespace("SummarizedExperiment", quietly = TRUE)) #se descarga los paquetes si es necesario
    BiocManager::install("SummarizedExperiment")

datos = read.csv("https://rest.xialab.ca/api/download/metaboanalyst/human_cachexia.csv") #se prepara archivo de datos
```


```{r 2, echo=TRUE}

summary(datos) #se observa la naturaleza de los datos
datos$Muscle.loss = as.factor(datos$Muscle.loss) #se pasa los grupos a factor
summary(datos) #se comprueba


id_pacientes = datos[, 1] #se guardan los ids
datos_filas = data.frame(ID_Paciente = id_pacientes)  #se crea un data frame de los ids
rownames(datos_filas) = id_pacientes  #se hace que las filas tengan nombre


datos_expresion_metabolitos = as.matrix(datos[, -1]) #se guardan los datos numéricos


metabolitos = data.frame(Tipos_metabolitos = colnames(datos_expresion_metabolitos))  #se crea un data frame de los distintos metabolitos estudiados
rownames(metabolitos) = colnames(datos_expresion_metabolitos)  ##se hace que las filas tengan nombre


library(SummarizedExperiment)
SExperiment = SummarizedExperiment( #se crea el SummarizedExperiment
  assays = list(counts = datos_expresion_metabolitos),
  rowData = datos_filas,
  colData = metabolitos
)
SummarizedExperiment::metadata(SExperiment) = list( #se añaden los metadatos
  descripcion = "Dataset con valores de metabolitos en pacientes control y con caquexia humana",
  fuente = "MetaboAnalyst",
  fecha = Sys.Date(),
  autor = "Xia Lab",
  filas = "Las filas representan los IDs de los individuos del estudio",
  columnas = "Las columnas representan los metabolitos medidos en los individuos",
  notas = "Los datos se dividen en dos subgrupos, los control y los que padecen caquexia. Los datos no están apareados. No se detectaron datos que falten. Dataset obtenido de https://rest.xialab.ca/api/download/metaboanalyst/human_cachexia.csv"
)

SExperiment #se ejecuta 

save(SExperiment, file = "Caquexia_SExperiment.Rda")
```


```{r 3, echo=TRUE}

summary(assay(SExperiment))
colData(SExperiment)
summary(rowData(SExperiment))
summary(colData(SExperiment))
summary(SExperiment)
```


```{r}
usethisgit init 
```

